name: Deploy Node.js App to GCP VM

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "
            export NVM_DIR=\$HOME/.nvm
            [ -s \"\$NVM_DIR/nvm.sh\" ] && \. \"\$NVM_DIR/nvm.sh\"
            if [ ! -d ~/apps/TransitEye-API ]; then
              git clone https://github.com/Yajme/TransitEye-API.git ~/apps/TransitEye-API
            fi
            cd ~/apps/TransitEye-API
            git pull origin main
            npm install --production
            pm2 stop TransitEye-API || true
            pm2 start index.js --name TransitEye-API
            pm2 save
          "
